version: '3'
services:
  workaround-mysql:
    container_name: workaround-mysql
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: workaround
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    networks:
      - my-network
  workaround:
    container_name: workaround
    depends_on: 
      - workaround-mysql
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workaround
    volumes:
      - ./:/workaround
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    links:
      - workaround-mysql
    networks:
      - my-network
#    restart: always
    ports:
      - "8080:8080"
networks:
  my-network:
    driver: bridge